version: '3'
services:
  redis:
    image: "redis:latest"
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=restapi
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "3306:3306"
  nginx:
    image: "nginx:latest"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./static:/tmp/src/webapp/static/
    network_mode: host
  webapp:
    image: "webapp:1.0"
    restart: always
    volumes:
      - ./static:/tmp/src/webapp/static/
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - BROKER_URL=redis://redis:6379/0
      - RESULT_BACKEND_URL=redis://redis:6379/1
      - NUM_WORKERS=4
    depends_on:
      - redis
      - mysql